source "https://rubygems.org"

gem "sinatra"
gem "slim"
gem "slim-pickins", path: "../slim-pickins"
gem "sqlite3"
gem "sinatra-contrib"
gem "puma"
gem "rackup"

group :development do
  gem "rerun"
end
